### ISSUE TITLE
certificate signed by unknown authority！

### ISSUE THREAD

**Issue by JohyC** [nojima/httpie-go#69]
When I httpie-go -v https://keelii.com/ I get an error！
![image](https://user-images.githubusercontent.com/38210128/122522010-10064080-d048-11eb-9306-a88bc6f23fee.png)

**Comment by golgoth31** [comment]
Hi,
a curl command gives me the same output:
```
❯ curl https://keelii.com/                                                                                                         
curl: (60) SSL certificate problem: unable to get local issuer certificate
```

I think the involved CA is not part of the default certificates of your OS. this is not related to httpie-go

**Comment by JohyC** [comment]
> Hi,
> a curl command gives me the same output:
> 
> ```
> ❯ curl https://keelii.com/                                                                                                         
> curl: (60) SSL certificate problem: unable to get local issuer certificate
> ```
> 
> I think the involved CA is not part of the default certificates of your OS. this is not related to httpie-go

Ok! I got it.Thanks for your reply.
